version: '3'
volumes:
    demo-yago-redis-conf-volume:
    demo-yago-redis-conf-volume:
    demo-yago-mock-api-logs-volume:
    demo-yago-proxy-logs-volume:
    demo-yago-external-api-logs-volume:
    demo-yago-postgres-data-volume:
    demo-yago-keycloak-themes-volume:
networks:
    demo-yago-network:
        driver: bridge
services:
    redis:
        container_name: demo-yago-mock-api-redis-container
        image: redis:7-alpine
        networks:
            - demo-yago-network
        ports:
            - 56379:6379
        volumes:
            - demo-yago-redis-conf-volume:/data
        restart: unless-stopped
    mock-api:
        container_name: demo-yago-mock-api-container
        image: docker-registry.server.kayser.dev/mock-api
        environment:
            - MOCK_API_REDIS_ADDRESS=demo-yago-mock-api-redis-container
            - MOCK_API_REDIS_PORT=6379
        ports:
            - 58080:8080
        networks:
            - demo-yago-network
        volumes:
            - demo-yago-mock-api-logs-volume:/logs
        depends_on:
            - redis
            - keycloak
        restart: unless-stopped
    mock-ui:
        container_name: demo-yago-mock-ui-container
        image: docker-registry.server.kayser.dev/mock-ui
        networks:
            - demo-yago-network
        ports:
            - 50080:80
        environment:
            - MOCK_API_BASE_URI=${MOCK_API_BASE_URI}
        depends_on:
            - mock-api
        restart: unless-stopped
    proxy:
        container_name: demo-yago-proxy-container
        image: docker-registry.server.kayser.dev/proxy
        networks:
            - demo-yago-network
        environment:
            - API_SERVER_URL=http://demo-yago-mock-api-container:8080
            - PROXY_LOGS_DIR=.
            - PROXY_APP_LOG_LEVEL=INFO
            - PROXY_3RD_PARTY_LOG_LEVEL=ERROR
            - PROXY_ROOT_LOG_LEVEL=ERROR
        ports:
            - 55000:5000
        volumes:
            - demo-yago-proxy-logs-volume:/logs
        depends_on:
            - mock-api
        restart: unless-stopped
    external-api:
        container_name: demo-yago-external-api-container
        image: docker-registry.server.kayser.dev/whiteapp
        networks:
            - demo-yago-network
        environment:
            - SPRING_PROFILES_ACTIVE=dev
        ports:
            - 58580:8080
        volumes:
            - demo-yago-external-api-logs-volume:/logs
        depends_on:
            - mock-api
        restart: unless-stopped
    postgres:
        container_name: demo-yago-postgres-container
        image: postgres
        networks:
            - demo-yago-network
        volumes:
            - demo-yago-postgres-data-volume:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=keycloak
            - POSTGRES_USER=keycloak
            - POSTGRES_PASSWORD=password
        ports:
            - 25432:5432
        restart: unless-stopped
    keycloak:
        container_name: demo-yago-keycloak-container
        image: quay.io/keycloak/keycloak:16.1.1
        networks:
            - demo-yago-network
        volumes:
            - demo-yago-keycloak-themes-volume:/opt/jboss/keycloak/themes
        environment:
            - DB_VENDOR=postgres
            - DB_ADDR=demo-yago-postgres-container
            - DB_DATABASE=keycloak
            - DB_USER=keycloak
            - DB_SCHEMA=public
            - DB_PASSWORD=password
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - KEYCLOAK_LOGLEVEL=INFO
            - JAVA_OPTS=-Dkeycloak.profile.feature.upload_scripts=enabled
        ports:
            - 48080:8080
        restart: unless-stopped
        depends_on:
            - postgres